#!/bin/sh

set -e

BACKUP_PREFIX=${BACKUP_PREFIX:-backup}

BACKUP_AWS_KEY=${BACKUP_AWS_KEY:-}
BACKUP_AWS_SECRET=${BACKUP_AWS_SECRET:-}
BACKUP_AWS_S3_PATH=${BACKUP_AWS_S3_PATH:-}

# prepare unique name with date like 2015-09-04T03-40-34UTC
backup_time="$(date -Iseconds | sed 's/:/-/g')"
if [ ! -d /backup/output ]; then
  mkdir /backup/output
fi
backup_archive=/backup/output/${BACKUP_PREFIX}.${backup_time}.tar.gz
# time to create an archive
tar -cvzf "${backup_archive}" /backup/input
# upload to amazon s3
if [[ ${BACKUP_AWS_S3_PATH} ]]; then
    s3cmd \
        --access_key="${BACKUP_AWS_KEY:?'BACKUP_AWS_KEY is required'}" \
        --secret_key="${BACKUP_AWS_SECRET:?'BACKUP_AWS_SECRET is required'}" \
        put "${backup_archive}" \
        "${BACKUP_AWS_S3_PATH}"
fi
# remove backup file
rm "${backup_archive}"
